# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-symlinks
    - id: check-added-large-files

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
    - id: shellcheck
    - id: shfmt

-   repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
    - id: shell-lint

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    - id: autopep8
      name: autopep8-default
      args: ["-i", "--ignore=E226,E24,W50,W690", "--max-line-length=150"]
      exclude: .*test_.*py$
    - id: autopep8
      name: autopep8-including-unit-tests
      args: ["-i", "--ignore=E226,E24,W50,W690,E402", "--max-line-length=150"]
